### ISSUE TITLE
panicked at 'assertion failed: !score.is_nan()'

### ISSUE THREAD

**Issue by zojw** [photondb/photondb#223]
```
thread 'photonio-worker/6' panicked at 'assertion failed: !score.is_nan()', src/page_store/strategy/mod.rs:54:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:48:5
   3: <photondb::page_store::strategy::MinDeclineRateStrategy as photondb::page_store::strategy::GcPickStrategy>::collect
             at /home/robi/Code/rust/photondb/src/page_store/strategy/mod.rs:54:9
   4: photondb::page_store::jobs::gc::GcCtx<E,R>::gc::{{closure}}
             at /home/robi/Code/rust/photondb/src/page_store/jobs/gc.rs:83:13
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   6: photondb::page_store::jobs::gc::GcCtx<E,R>::run::{{closure}}
             at /home/robi/Code/rust/photondb/src/page_store/jobs/gc.rs:65:30
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   8: photonio_uring::task::raw::poll::{{closure}}
             at /home/robi/.cargo/git/checkouts/photonio-4d2b22930312944b/fa68ae8/photonio-uring/src/task/raw.rs:202:65
   9: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panic/unwind_safe.rs:271:9
  10: std::panicking::try::do_call
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:464:40
  11: std::panicking::try
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:428:19
```

**Comment by w41ter** [comment]
I also encountered this issue, let me follow it up.
