### ISSUE TITLE
panicked at 'The reclamied file 34 has active pages'

### ISSUE THREAD

**Issue by w41ter** [photondb/photondb#239]
```log
[2022-11-08T12:24:23Z DEBUG photondb::page_store::strategy] Min decline rate strategy scores: [FileScore { score: 12937502.183856335, effective_rate: 0.9999016740837005, [272/4451]
ify: 1.6382464357250306e-6, file_id: 35 }, FileScore { score: 8510.157789679954, effective_rate: 0.9937804176113808, write_amplify: 3.208517710101981e-8, file_id: 31 }, FileScore { score: 25.21559370420057, effective_rate: 0.8765659312954175, write_amplify: 1.542835571968302e-7, file_id: 34 }]                                                                  
[2022-11-08T12:24:23Z INFO  photondb::page_store::jobs::gc] next version 37 pick 1 page files by strategy for gc                                                                    [2022-11-08T12:24:23Z INFO  photondb::page_store::jobs::gc] Rewrite file 34 with 1 active pages, 21 dealloc pages, latest 1932 microseconds                                         
[2022-11-08T12:24:23Z INFO  photondb::page_store::jobs::gc] gc version finished, cost 2105 microseconds                                                                             [2022-11-08T12:24:24Z INFO  photondb::page_store::write_buffer] Seal write buffer 36, 0 pending writers, allocated 127366104 bytes, usage 0.9489514231681824                        
[2022-11-08T12:24:24Z DEBUG photondb::page_store::version] Install new buffer 37, buffer set range 36..38                                                                           [2022-11-08T12:24:24Z DEBUG photondb::page_store::jobs::flush] write buffer 36 is flushable                                                                                         [2022-11-08T12:24:24Z DEBUG photondb::page_store::jobs::flush] begin flush version with next file id 37                                                                             [2022-11-08T12:24:24Z INFO  photondb::page_store::jobs::flush] Flush write buffer 36 to page file, num_records: 26577 num_tombstone_records: 0 num_dealloc_pages: 24 num_skip_pages: 17747 data_size: 68751820
[2022-11-08T12:24:24Z INFO  photondb::page_store::jobs::flush] Flush output file 36 with 1458578 bytes, 13 active pages, 24 dealloc pages, lasted 40412 microseconds      
          
thread 'tokio-runtime-worker' panicked at 'The reclamied file 34 has active pages', src/page_store/jobs/flush.rs:243:21                                                             stack backtrace:                                                                                                                                                                       
0: rust_begin_unwind                                                                                                                                                                          
at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5                                                                                     1: core::panicking::panic_fmt                                                                                                                                                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14                                                                                   2: photondb::page_store::jobs::flush::assert_files_are_deletable                                                                                                                              at ./src/page_store/jobs/flush.rs:243:21                                                                                                                                  
3: photondb::page_store::jobs::flush::drain_obsoleted_files                                                                                                                                   at ./src/page_store/jobs/flush.rs:219:5                                                                                                                                   
4: photondb::page_store::jobs::flush::FlushCtx<E>::flush::{{closure}}
             at ./src/page_store/jobs/flush.rs:101:31                                                                                                                                  
5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19                                                                                   6: photondb::page_store::jobs::flush::FlushCtx<E>::run::{{closure}}
             at ./src/page_store/jobs/flush.rs:73:62                                                                                                                                   
7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19        
```

**Comment by w41ter** [comment]
Here is some log would help to positioning problem:

```
[2022-11-09T06:37:14Z INFO  photondb::page_store::page_txn] replace page 1666 old 8590255808 new 8590256000, dealloc [8590255808, 4428971656, 4428438816, 4428210936, 4428193664]
[2022-11-09T06:37:21Z INFO  photondb::page_store::jobs::gc] Rewrite 2 page id 1666 page addr 8590256000
replace page 1666 old 8617064168 new 17192960240, dealloc [8617064168, 8614575304]
[2022-11-09T06:37:21Z INFO  photondb::page_store::jobs::gc] Rewrite 2 page id 1666 page addr 8614575304
[2022-11-09T06:37:21Z INFO  photondb::page_store::jobs::gc] Rewrite 2 page id 1666 page addr 8617064168
thread 'tokio-runtime-worker' panicked at 'The reclamied file 2 has active pages, first is 8590256000', photondb/src/page_store/jobs/flush.rs:244:21
```

It seems that page with addr `8590256000` is not found during `rewrite_page`. /cc @huachaohuang

**Comment by w41ter** [comment]
```
[2022-11-09T06:57:31Z INFO  photondb::page_store::page_txn] update page 2139 old 8610279224 new 8610877824
[2022-11-09T06:57:31Z INFO  photondb::page_store::page_txn] update page 2139 old 8610877824 new 8610935312
[2022-11-09T06:57:35Z INFO  photondb::page_store::page_txn] update page 2139 old 8610935312 new 12897165968
[2022-11-09T06:57:35Z INFO  photondb::page_store::page_txn] update page 2139 old 12897165968 new 12899549872
[2022-11-09T06:57:35Z INFO  photondb::page_store::page_txn] replace page 2139 old 12899549872 new 12899550032, dealloc [12899549872, 12897165968, 8610935312, 8610877824]

... 

[2022-11-09T06:57:36Z INFO  photondb::page_store::page_txn] update page 2139 old 12925658136 new 12925952072
[2022-11-09T06:57:36Z INFO  photondb::page_store::page_txn] replace page 2139 old 12925952072 new 12925952264, dealloc [12925952072, 12925658136]

...

[2022-11-09T06:57:39Z INFO  photondb::page_store::jobs::gc] Rewrite 2 page id 2139 page addr 8610279224
[2022-11-09T06:57:39Z INFO  photondb::page_store::page_txn] replace page 2139 old 12925952264 new 17188930336, dealloc [12925952264, 12925078528]

...

thread 'tokio-runtime-worker' panicked at 'The reclamied file 2 has active pages, first is 8610279224', photondb/src/page_store/jobs/flush.rs:244:21
```

According the logs, page `8610279224` isn't belongs to page id `2139` but have not entered the dealloc pages.

**Comment by w41ter** [comment]
It appeared again:

```
thread 'tokio-runtime-worker' panicked at 'The reclamied file 548 has active pages', photondb/src/page_store/jobs/flush.rs:223:21                                                   stack backtrace:                                                                                                                                                                       0: rust_begin_unwind                                                                                                                                                                          at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14
   2: photondb::page_store::jobs::flush::assert_files_are_deletable
             at ./photondb/src/page_store/jobs/flush.rs:223:21
   3: photondb::page_store::jobs::flush::drain_obsoleted_files
             at ./photondb/src/page_store/jobs/flush.rs:199:5
   4: photondb::page_store::jobs::flush::FlushCtx<E>::flush::{{closure}}
             at ./photondb/src/page_store/jobs/flush.rs:91:31
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   6: photondb::page_store::jobs::flush::FlushCtx<E>::run::{{closure}}
             at ./photondb/src/page_store/jobs/flush.rs:67:62
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   8: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
   9: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
  10: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
  11: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panic/unwind_safe.rs:271:9
  13: std::panicking::try::do_call
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:464:40
  14: __rust_try
  15: std::panicking::try
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:428:19
  16: std::panic::catch_unwind
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panic.rs:137:14
  17: tokio::runtime::task::harness::poll_future
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18
  18: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27
```

**Comment by w41ter** [comment]
The key infos looks like the previous issue:

```
[2022-11-11T02:41:55Z INFO  photondb::page_store::jobs::gc] Rewrite page 5823 addr 270593170448
[2022-11-11T02:41:55Z INFO  photondb::page_store::page_txn] Replace page 5823 old 309285464304 new 309285782152 addrs [309285464304]
thread 'tokio-runtime-worker' panicked at 'The reclamied file 63 has active pages, first addr is 270593170448', photondb/src/page_store/jobs/flush.rs:225:21
```

The rewrite page 5823 with addr 270593170448 is not deallocated.

**Comment by huachaohuang** [comment]
@w41ter Thanks, I will check it later.

**Comment by w41ter** [comment]
I reproduced this issue again and found some logs:

```
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048045457784 new 1048045457944
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1048045457784, 1048045457464, 1048038996400, 1048032765136, 1048032750656]
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048045457944 new 1048045506832
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048045506832 new 1048047065856
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048047065856 new 1048048683744
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048048683744 new 1048048691768
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048048691768 new 1048048691928
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1048048691768, 1048048683744, 1048047065856, 1048045506832]
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048048691928 new 1048048707840
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048048707840 new 1048051910480
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048051910480 new 1048055061608
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048055061608 new 1048055061768
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1048055061608, 1048051910480, 1048048707840, 1048048691928]
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048055061768 new 1048055118792
[2022-11-11T03:25:06Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048055118792 new 1048061500816
[2022-11-11T03:25:06Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048061500816 new 1048064685968
[2022-11-11T03:25:06Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048064685968 new 1048064686128
[2022-11-11T03:25:06Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1048064685968, 1048061500816, 1048055118792]
[2022-11-11T03:25:06Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048064686128 new 1048064701280
[2022-11-11T03:25:06Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048064701280 new 1048067868712
[2022-11-11T03:25:06Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048067868712 new 1048067868872
[2022-11-11T03:25:06Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1048067868712, 1048064701280, 1048064686128, 1048055061768]
[2022-11-11T03:25:06Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048067868872 new 1048067907144
[2022-11-11T03:25:33Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266320832792
[2022-11-11T03:25:33Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266337273008
[2022-11-11T03:25:33Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266342118056
[2022-11-11T03:25:33Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266343834424
[2022-11-11T03:25:33Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 313544262760
[2022-11-11T03:25:33Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 313546179408
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 876305667776
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 876305683392
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880576895720
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880578354864
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880581317232
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880581349080
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 884891734112
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 884894789720
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 884894797240
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 889092250456
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 889092453272
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1043806605056
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1043809813848
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1048045457944
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1048067868872
[2022-11-11T03:25:34Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1048067907144
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340045569112 new 1340045613728
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340045613728 new 1340049779928
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340049779928 new 1340050636640
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340050636640 new 1340050665144
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340050665144 new 1340050665304
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340050665144, 1340050636640, 1340049779928, 1340045613728]
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340050665304 new 1340052272264
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340052272264 new 1340052308600
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340052308600 new 1340052340016
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340052340016 new 1340052340176
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340052340016, 1340052308600, 1340052272264, 1340050665304]
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340052340176 new 1340052360224
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340052360224 new 1340052373160
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340052373160 new 1340052412704
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340052412704 new 1340052413024
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340052412704, 1340052373160, 1340052360224]
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340052413024 new 1340053991072
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340053991072 new 1340054022280
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340054022280 new 1340054022440
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340054022280, 1340053991072, 1340052413024, 1340052340176]
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340054022440 new 1340054024368
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340054024368 new 1340058865536
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340058865536 new 1340060526192
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340060526192 new 1340060526352
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340060526192, 1340058865536, 1340054024368]
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340060526352 new 1340061300152
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340061300152 new 1340061310952
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340061310952 new 1340061311112
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340061310952, 1340061300152, 1340060526352]
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340061311112 new 1340062142240
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340062142240 new 1340062213576
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340062213576 new 1340062213896
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340062213576, 1340062142240]
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340062213896 new 1340062214216
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340062214216 new 1340062214536
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340062214216, 1340062213896, 1340061311112, 1340054022440]
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340062214536 new 1340062257632
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340062257632 new 1340063871256
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340063871256 new 1340063920200
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340063920200 new 1340063920360
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340063920200, 1340063871256, 1340062257632]
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340063920360 new 1340064736592
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340064736592 new 1340066377112
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340066377112 new 1340066377272
[2022-11-11T03:28:17Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340066377112, 1340064736592, 1340063920360]
[2022-11-11T03:28:58Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266320832792
[2022-11-11T03:28:58Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266337273008
[2022-11-11T03:28:58Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266342118056
[2022-11-11T03:28:58Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266343834424
[2022-11-11T03:28:58Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 313544262760
[2022-11-11T03:28:58Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 313546179408
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 876305667776
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 876305683392
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880576895720
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22387 to addr 880578354864
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880581317232
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880581349080
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 884891734112
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 884894789720
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 884894797240
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 889092250456
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 889092453272
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1043806605056
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1043809813848
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1048045457944
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1048067868872
[2022-11-11T03:28:59Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1048067907144
[2022-11-11T03:29:00Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1340045569112
[2022-11-11T03:29:00Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1340062214536
[2022-11-11T03:29:00Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1340066377272
[2022-11-11T03:30:05Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266320832792
[2022-11-11T03:30:05Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266337273008
[2022-11-11T03:30:05Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266342118056
[2022-11-11T03:30:05Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 266343834424
[2022-11-11T03:30:05Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 313544262760
[2022-11-11T03:30:05Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 313546179408
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 876305667776
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 876305683392
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880576895720
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880578354864
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880581317232
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 880581349080
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 884891734112
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 884894789720
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 884894797240
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 889092250456
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 889092453272
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1043806605056
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1043809813848
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1048045457944
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1048067868872
[2022-11-11T03:30:06Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1048067907144
[2022-11-11T03:30:07Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1340045569112
[2022-11-11T03:30:07Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1340062214536
[2022-11-11T03:30:07Z INFO  photondb::page_store::recover] Recover set page 22386 to addr 1340066377272
[2022-11-11T03:30:08Z INFO  photondb::page_store::jobs::gc] Rewrite page 22386 addr 1048045457944
[2022-11-11T03:30:08Z INFO  photondb::page_store::page_txn] Update page 22386 old 1340066377272 new 1460296012880
[2022-11-11T03:30:08Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1340066377272, 1340062214536, 1340045569112]
[2022-11-11T03:30:08Z INFO  photondb::page_store::jobs::gc] Rewrite page 22386 addr 1048067868872
[2022-11-11T03:30:08Z INFO  photondb::page_store::jobs::gc] Rewrite page 22386 addr 1048067907144
thread 'tokio-runtime-worker' panicked at 'The reclamied file 244 has active pages, first addr is 1048045457944', photondb/src/page_store/jobs/flush.rs:225:21
```

The `Recover xxx` is logged at:

```Rust
diff --git a/photondb/src/page_store/recover.rs b/photondb/src/page_store/recover.rs
index 1d646a7..a924dea 100644
--- a/photondb/src/page_store/recover.rs
+++ b/photondb/src/page_store/recover.rs
@@ -80,6 +80,7 @@ impl<E: Env> PageStore<E> {
             let meta_reader = page_files.open_meta_reader(file_id).await?;
             for (page_addr, page_id) in meta_reader.read_page_table().await? {
                 table.set(page_id, page_addr);
+                log::info!("Recover set page {page_id} to addr {page_addr}");
             }
         }
         Ok(table)
```

According the logs, the `1048045457944` was installed into page `22386` but updated to `1048045506832` immedately, then the successor replace page `22386` didn't contains `1048045457944`:

```
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048045457784 new 1048045457944
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1048045457784, 1048045457464, 1048038996400, 1048032765136, 1048032750656]
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048045457944 new 1048045506832
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048045506832 new 1048047065856
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048047065856 new 1048048683744
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048048683744 new 1048048691768
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Update page 22386 old 1048048691768 new 1048048691928
[2022-11-11T03:25:05Z INFO  photondb::page_store::page_txn] Replace page 22386 dealloc addrs [1048048691768, 1048048683744, 1048047065856, 1048045506832]
```

**Comment by huachaohuang** [comment]
OK, I can reproduce it once. Have no clue yet.

**Comment by huachaohuang** [comment]
[821.txt](https://github.com/photondb/photondb/files/9986603/821.txt)

It seems that the page is re-inserted after the db is re-opened, maybe something is wrong with the recovered page table.

**Comment by huachaohuang** [comment]
Oh, I see, the page table needs to be scanned to construct the free list after recovery.

**Comment by huachaohuang** [comment]
> Oh, I see, the page table needs to be scanned to construct the free list after recovery.

Let me see how to fix this in a reasonable way.
