### ISSUE TITLE
panicked at 'File 20 is not exists'

### ISSUE THREAD

**Issue by w41ter** [photondb/photondb#240]
```log
[2022-11-08T12:43:57Z DEBUG photondb::page_store::jobs::flush] write buffer 20 is not flushable, current buffer state BufferState { sealed: false, num_writer: 1, allocated: 12569928 } wait
[2022-11-08T12:43:57Z INFO  photondb::page_store::write_buffer] Seal write buffer 20, 0 pending writers, allocated 125704360 bytes, usage 0.9365704655647278
[2022-11-08T12:43:57Z DEBUG photondb::page_store::version] Install new buffer 21, buffer set range 20..22
[2022-11-08T12:43:57Z DEBUG photondb::page_store::jobs::flush] write buffer 20 is flushable
[2022-11-08T12:43:57Z DEBUG photondb::page_store::jobs::flush] begin flush version with next file id 21
[2022-11-08T12:43:57Z INFO  photondb::page_store::jobs::flush] Flush write buffer 20 to page file, num_records: 8 num_tombstone_records: 0 num_dealloc_pages: 0 num_skip_pages: 0 data_size: 1144
[2022-11-08T12:43:57Z INFO  photondb::page_store::jobs::flush] Flush output file 20 with 1456 bytes, 8 active pages, 0 dealloc pages, lasted 10698 microseconds
[2022-11-08T12:43:57Z INFO  photondb::page_store::jobs::flush] Apply new file 20 dealloc pages []
[2022-11-08T12:43:57Z DEBUG photondb::page_store::jobs::flush] Flush install version with new file 20, total 11818 microseconds
[2022-11-08T12:43:57Z DEBUG photondb::page_store::version] Switch version from 20 to 21
[2022-11-08T12:43:57Z DEBUG photondb::page_store::version] Release write buffer 20
[2022-11-08T12:43:57Z DEBUG photondb::page_store::jobs::flush] Flush file 20 is success
[2022-11-08T12:43:57Z DEBUG photondb::page_store::jobs::flush] write buffer 21 is not flushable, current buffer state BufferState { sealed: false, num_writer: 1, allocated: 12570656 } wait
thread 'tokio-runtime-worker' panicked at 'File 20 is not exists', /home/patrick/workspace/montplex/photondb/src/page_store/page_txn.rs:85:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14
   2: photondb::page_store::page_txn::Guard<E>::read_page::{{closure}}
             at ./src/page_store/page_txn.rs:85:17
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   4: photondb::tree::TreeTxn<E>::walk_page::{{closure}}
             at ./src/tree/mod.rs:261:59
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   6: photondb::tree::TreeTxn<E>::collect_consolidation_info::{{closure}}
             at ./src/tree/mod.rs:670:9
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   8: photondb::tree::TreeTxn<E>::consolidate_page_impl::{{closure}}
             at ./src/tree/mod.rs:603:58
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  10: photondb::tree::TreeTxn<E>::consolidate_page::{{closure}}
             at ./src/tree/mod.rs:582:21
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  12: photondb::tree::TreeTxn<E>::try_rewrite_page::{{closure}}
             at ./src/tree/mod.rs:572:36
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  14: photondb::tree::TreeTxn<E>::rewrite_page::{{closure}}
             at ./src/tree/mod.rs:562:44
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  16: photondb::tree::<impl photondb::page_store::jobs::gc::RewritePage<E> for alloc::sync::Arc<photondb::tree::Tree>>::rewrite::{{closure}}
             at ./src/tree/mod.rs:87:33
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  18: photondb::page_store::jobs::gc::GcCtx<E,R>::rewrite_active_pages::{{closure}}
             at ./src/page_store/jobs/gc.rs:216:50
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  20: photondb::page_store::jobs::gc::GcCtx<E,R>::rewrite_file::{{closure}}
             at ./src/page_store/jobs/gc.rs:176:13
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  22: photondb::page_store::jobs::gc::GcCtx<E,R>::rewrite_files::{{closure}}
             at ./src/page_store/jobs/gc.rs:160:63

```

**Comment by w41ter** [comment]
Reason: 
`File 31 is not exists, version buffer ranges 29..31, buffer set ranges [32, 33)`

**Comment by w41ter** [comment]
@zojw This is another issue, please open a new one. I will track it later.
