### ISSUE TITLE
 panicked at 'split page delta must exist'

### ISSUE THREAD

**Issue by w41ter** [photondb/photondb#253]
```
thread 'tokio-runtime-worker' panicked at 'split page delta must exist', photondb/src/tree/mod.rs:806:10                                                                            stack backtrace:                                                                                                                                                                       0: rust_begin_unwind                                                                                                                                                                          at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5                                                                                     1: core::panicking::panic_fmt                                                                                                                                                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14                                                                                   2: core::panicking::panic_display                                                                                                                                                             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:72:5                                                                                     3: core::panicking::panic_str                                                                                                                                                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:56:5                                                                                     4: core::option::expect_failed                                                                                                                                                                at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/option.rs:1873:5                                                                                      5: core::option::Option<T>::expect                                                                                                                                                            at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/option.rs:738:21                                                                                      6: photondb::tree::split_delta_from_page
             at ./photondb/src/tree/mod.rs:804:5
   7: photondb::tree::TreeTxn<E>::collect_consolidation_info::{{closure}}::{{closure}}
             at ./photondb/src/tree/mod.rs:675:46
   8: photondb::tree::TreeTxn<E>::walk_page::{{closure}}
             at ./photondb/src/tree/mod.rs:272:16
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  10: photondb::tree::TreeTxn<E>::collect_consolidation_info::{{closure}}
             at ./photondb/src/tree/mod.rs:685:9
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  12: photondb::tree::TreeTxn<E>::consolidate_page_impl::{{closure}}
             at ./photondb/src/tree/mod.rs:617:58
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll                                                                                                         		 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19                                                                                  14: photondb::tree::TreeTxn<E>::consolidate_page::{{closure}}                                                                                                                                  at ./photondb/src/tree/mod.rs:596:21                                                                                                                                     15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll                                                                                                         at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19                                                                                  16: photondb::tree::TreeTxn<E>::try_rewrite_page::{{closure}}                                                                                                                                  at ./photondb/src/tree/mod.rs:586:36                                                                                                                                     17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll                                                                                                         at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19                                                                                  18: photondb::tree::TreeTxn<E>::rewrite_page::{{closure}}                                                                                                                                      at ./photondb/src/tree/mod.rs:576:44                                                                                                                                     19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll                                                                                                         at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19                                                                                  20: photondb::tree::<impl photondb::page_store::jobs::gc::RewritePage<E> for alloc::sync::Arc<photondb::tree::Tree>>::rewrite::{{closure}}
             at ./photondb/src/tree/mod.rs:87:33
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  22: photondb::page_store::jobs::gc::GcCtx<E,R>::rewrite_active_pages::{{closure}}
             at ./photondb/src/page_store/jobs/gc.rs:216:54
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  24: photondb::page_store::jobs::gc::GcCtx<E,R>::rewrite_file::{{closure}}
             at ./photondb/src/page_store/jobs/gc.rs:175:13
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  26: photondb::page_store::jobs::gc::GcCtx<E,R>::rewrite_files::{{closure}}
             at ./photondb/src/page_store/jobs/gc.rs:159:63
```

**Comment by huachaohuang** [comment]
This is because it uses the wrong page kind for consolidated pages. The page kind should be always `PageKind::Data` instead of inheriting the page kind from the first page.
