### ISSUE TITLE
panicked at 'The reclaimed page file 25 has active pages'

### ISSUE THREAD

**Issue by w41ter** [photondb/photondb#348]
```
thread 'tokio-runtime-worker' panicked at 'The reclaimed page file 25 has active pages', photondb/src/page_store/jobs/flush.rs:242:17
stack backtrace:  
   0: rust_begin_unwind
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5                                                                                     1: core::panicking::panic_fmt
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14                                                                                   2: photondb::page_store::jobs::flush::assert_files_are_deletable
             at ./photondb/src/page_store/jobs/flush.rs:242:17
   3: photondb::page_store::jobs::flush::drain_obsoleted_files
             at ./photondb/src/page_store/jobs/flush.rs:218:5
   4: photondb::page_store::jobs::flush::FlushCtx<E>::save_and_install_version::{{closure}}                                                                                                      at ./photondb/src/page_store/jobs/flush.rs:106:36
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   6: photondb::page_store::jobs::flush::FlushCtx<E>::flush::{{closure}}
             at ./photondb/src/page_store/jobs/flush.rs:91:13
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   8: photondb::page_store::jobs::flush::FlushCtx<E>::run::{{closure}}
             at ./photondb/src/page_store/jobs/flush.rs:67:52
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
  10: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17                                                 [91/4081]
  11: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9                                                           12: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13                                                            13: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19                                                         14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once                                                                                              at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panic/unwind_safe.rs:271:9                                                                           15: std::panicking::try::do_call
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:464:40                                                                                   16: __rust_try
  17: std::panicking::try
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:428:19                                                                                   18: std::panic::catch_unwind
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panic.rs:137:14                                                                                       19: tokio::runtime::task::harness::poll_future
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:468:18                                                         20: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:104:27                                                         21: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:57:15                                                          22: tokio::runtime::task::raw::poll
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:194:5                                                              23: tokio::runtime::task::raw::RawTask::poll
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/raw.rs:134:18                                                             24: tokio::runtime::task::LocalNotified<S>::run                                                                                                                                                at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/mod.rs:385:9                                                              25: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/worker.rs:421:13
  26: tokio::coop::with_budget::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9                                                                          27: std::thread::local::LocalKey<T>::try_with
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/thread/local.rs:446:16
  28: std::thread::local::LocalKey<T>::with
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/thread/local.rs:422:9                                                                                 29: tokio::coop::with_budget
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:95:5
  30: tokio::coop::budget
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
```

**Comment by w41ter** [comment]
It caused by 
![image](https://user-images.githubusercontent.com/7908062/204471064-f6525225-eafb-43cd-8283-618f3f92d48a.png)
